version: 3

images:
  base_image:
    name: quay.io/almalinux/almalinux:9

dependencies:
  ansible_core:
    package_pip: ansible
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
  - openssh-clients
  - sshpass
  galaxy:
    collections:
      - community.postgresql  # PostgreSQL management
      - community.mysql       # MySQL management
      - community.docker      # Docker management
