---
- name: Backup and remove sha1 from opensshserver.config
  hosts: all
  become: yes
  vars:
    - conf_path: "/usr/share/crypto-policies/DEFAULT/opensshserver.txt"

  tasks:
    - name: Generate backup file path based on hash
      stat:
        path: "{{ conf_path }}"
      register: conf_stat

    - name: Set backup file variable
      set_fact:
        conf_back: "{{ conf_path }}.{{ conf_stat.stat.checksum }}.bak"

    - name: Backup the config file if no backup exists
      copy:
        src: "{{ conf_path }}"  # Copie le fichier de configuration original
        dest: "{{ conf_back }}"  # Sauvegarde avec un nom unique basé sur le hash du contenu
        remote_src: yes
        force: no

    - name: Remove sha1 values from CRYPTO_POLICY in opensshserver.config
      replace:
        path: "{{ conf_path }}"
        regexp: ',?[^,]*sha1[^, ]*'  # Supprime toutes les références à "sha1" dans la politique de chiffrement
        replace: ''
      register: config_changed

    - name: Restart SSH service if configuration was modified
      block:
        - name: Validate that no sha1 remains
          command: grep -E 'sha1' "{{ conf_path }}"  # Vérifie si "sha1" est toujours présent
          register: sha1_check
          failed_when: sha1_check.rc == 0  # Échoue si "sha1" est trouvé

        - name: Attempt to restart SSH service
          service:
            name: sshd
            state: restarted  # Redémarre le service SSH après modification
          register: ssh_restart
          when: config_changed.changed

      rescue:
        - name: Rollback - Restore the backup file
          copy:
            src: "{{ conf_back }}"  # Restaure la configuration originale en cas d'échec
            dest: "{{ conf_path }}"
            remote_src: yes

        - name: Delete the backup file if SSH restarted successfully
          file:
            path: "{{ conf_back }}"  # Supprime le fichier de sauvegarde
            state: absent

        - name: Restart SSH service after rollback
          service:
            name: sshd
            state: restarted  # Redémarre SSH après restauration
